
// DO NOT EDIT THIS FILE
// This file is automatically generated from the webgme-setup-tool.
'use strict';


var config = require('webgme/config/config.default'),
    validateConfig = require('webgme/config/validator');


// The paths can be loaded from the webgme-setup.json
config.plugin.basePaths.push('src/plugins');
config.plugin.basePaths.push('node_modules/formula/src/plugins');
config.addOn.basePaths.push('src/addons');
config.visualization.decoratorPaths.push('src/decorators');

config.addOn.enable = true;

config.visualization.panelPaths.push('node_modules/formula/src/visualizers/panels');


// Visualizer descriptors
config.visualization.visualizerDescriptors.push('./src/visualizers/Visualizers.json');
// Add requirejs paths
config.requirejsPaths = {
  'FormulaEditor': 'panels/FormulaEditor/FormulaEditorPanel',
  'GenFORMULA': 'node_modules/formula/src/plugins/GenFORMULA',
  'panels': './src/visualizers/panels',
  'widgets': './src/visualizers/widgets',
  'panels/FormulaEditor': './node_modules/formula/src/visualizers/panels/FormulaEditor',
  'widgets/FormulaEditor': './node_modules/formula/src/visualizers/widgets/FormulaEditor'
};


config.mongo.uri = 'mongodb://127.0.0.1:27017/gridlabd';
validateConfig(config);
module.exports = config;
