autoclean=TRUE; // autoclean enable flag
autostart_gui=TRUE; // automatic GUI start enable flag
browser=firefox; // browser selection
check_version=FALSE; // check version enable flag
checkpoint_file=""; // checkpoint file base name
checkpoint_interval=0; // checkpoint interval
checkpoint_keepall=FALSE; // checkpoint file keep enable flag
checkpoint_seqnum=0; // checkpoint sequence number
checkpoint_type=NONE; // checkpoint type usage flag
clock=2000-01-01 00:00:00 UTC; // global clock
command_line="/usr/local/bin/gridlabd.bin --globals"; // command line
compileonly=FALSE; // compile only enable flag
complex_format=%+lg%+lg%c; // format for writing complex values
dateformat=ISO; // date format string
debug=FALSE; // debug output status flag
debugger=FALSE; // debugger enable flag
delta_current_clock=+0; // Absolute delta time (global clock offset)
deltaclock=0; // cumulative delta runtime with respect to the global clock
deltamode_iteration_limit=10; // iteration limit for each delta timestep (object and interupdate)
deltamode_maximumtime=3600000000000; // maximum time (ns) deltamode can run
deltamode_timestep=10000000; // uniform step size for deltamode simulations
deltamode_updateorder=""; // order in which modules are update in deltamode
double_format=%+lg; // format for writing double values
dumpall=FALSE; // dumpall enable flag
dumpfile=gridlabd.xml; // dump filename
environment=batch; // operating environment
execdir=/usr/local/bin; // directory where executable binary was found
force_compile=0; // force recompile enable flag
gdb=FALSE; // gdb enable flag
gdb_window=FALSE; // gdb window enable flag
hostaddr=127.0.0.1; // unused
hostname=localhost; // unused
include=""; // include folder path
infourl=http://gridlab-d.sourceforge.net/info.php?title=Special:Search/; // URL to use for obtaining online help
init_max_defer=64; // deferred initialization limit
init_sequence=DEFERRED; // initialization sequence control flag
inline_block_size=1048576; // inline code block size
iteration_limit=100; // iteration limit
kmlfile=""; // KML output file name
mainloop_state=INIT; // main sync loop state flag
master=""; // master server hostname
master_port=0; // master server port number
maximum_synctime=60; // maximum sync time for deltamode
minimum_timestep=1; // minimum timestep
modelname=""; // model name
module_compiler_flags=NONE; // module compiler flags
mt_analysis=FALSE; // perform multithread profile optimization analysis
multirun_conn=NONE; // unused
multirun_mode=STANDALONE; // multirun enable flag
no_deprecate=FALSE; // suppress deprecated usage message enable flag
nolocks=FALSE; // locking disable flag
object_format=%s:%d; // format for writing anonymous object names
object_scan=%[^:]:%d; // format for reading anonymous object names
object_tree_balance=FALSE; // object index tree balancing enable flag
pauseat=NEVER; // pause at time
pauseatexit=FALSE; // pause at exit flag
platform=LINUX; // operating platform
profiler=FALSE; // profiler enable flag
quiet=FALSE; // quiet output status flag
random_number_generator=RNG3; // random number generator version control flag
randomseed=0; // random number generator seed value
relax_naming_rules=FALSE; // relax object naming rules enable flag
return_code=0; // unused
run_powerworld=FALSE; // boolean that that says your system is set up correctly to run with PowerWorld
run_realtime=FALSE; // realtime enable flag
runchecks=FALSE; // runchecks enable flag
sanitize=NAMES|POSITIONS; // sanitize process options
sanitize_index=.txt; // sanitization index file spec
sanitize_offset=""; // sanitization lat/lon offset
sanitize_prefix=GLD_; // sanitized name prefix
savefile=""; // save filename
server_portnum=6267; // server port number
server_quit_on_close=FALSE; // server quit on connection closed enable flag
show_progress=TRUE; // show progress enable flag
signal_timeout=5000; // unused
simulation_mode=INIT; // current time simulation type
skipsafe=FALSE; // skip sync safe enable flag
slave_id=0; // unused
slave_port=6267; // unused
starttime=2000-01-01 00:00:00 UTC; // simulation start time
stoptime=NEVER; // simulation stop time
streaming_io=FALSE; // streaming I/O enable flag
strictnames=TRUE; // strict global name enable flag
suppress_repeat_messages=TRUE; // suppress repeated messages enable flag
technology_readiness_level=UNKNOWN; // technology readiness level
test=FALSE; // test enable flag
testoutputfile=test.txt; // filename for test output
threadcount=1; // number of threads to use while using multicore
tmp=/home/jeb/.gridlabd/tmp; // temporary folder name
trace=""; // trace function list
urlbase=http://www.gridlabd.org/; // url base string
validate=TSTD|RALL; // validation test options
verbose=FALSE; // verbose enable flag
version.branch=trunk; // branch name
version.build=5307; // build number
version.major=4; // major version
version.minor=0; // minor version
version.patch=0; // patch number
warn=TRUE; // warning output status flag
website=http://www.gridlabd.org/; // url base string (deprecated)
workdir=/home/jeb/Repositories/webgme-gridlabd; // working directory
xml_encoding=8; // XML data encoding
